"""Set is_admin not null with default

Revision ID: 05dc8a1bf552
Revises: cf828c575680
Create Date: 2025-02-04 07:40:54.832015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dc8a1bf552'
down_revision: Union[str, None] = 'cf828c575680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure no NULL values exist before altering the column
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
