"""added_display_order_in_user_recitation_table

Revision ID: 070d63ce5dcc
Revises: 77f12151114b
Create Date: 2025-11-15 01:35:43.100196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '070d63ce5dcc'
down_revision: Union[str, None] = '77f12151114b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_featured_day_cache_expires', table_name='featured_day_cache')
    op.drop_table('featured_day_cache')
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    op.add_column('user_recitations', sa.Column('display_order', sa.Integer(), nullable=False))
    op.create_index('idx_user_recitations_user_text_text', 'user_recitations', ['text_id'], unique=False)
    op.drop_constraint('fk_user_recitations_user', 'user_recitations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_user_recitations_user', 'user_recitations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_user_recitations_user_text_text', table_name='user_recitations')
    op.drop_column('user_recitations', 'display_order')
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('featured_day_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='featured_day_cache_pkey')
    )
    op.create_index('idx_featured_day_cache_expires', 'featured_day_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###

