"""removed user_recitation table

Revision ID: 09bd37b1b454
Revises: 5cd30a42ee8b
Create Date: 2025-11-11 15:29:12.896869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bd37b1b454'
down_revision: Union[str, None] = '5cd30a42ee8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the legacy user_recitation table
    op.drop_table('user_recitation')

    # Keep the plans search index refresh
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index(
        'idx_plans_search',
        'plans',
        [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")],
        unique=False,
        postgresql_using='gin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the legacy user_recitation table and its indexes
    op.create_table(
        'user_recitation',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('recitation_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['recitation_id'], ['recitation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'recitation_id', name='uq_user_recitation_user_recitation'),
    )
    op.create_index(
        'idx_user_recitation_user_recitation_recitation',
        'user_recitation',
        ['recitation_id'],
        unique=False
    )
    op.create_index(
        'idx_user_recitation_user_recitation_user',
        'user_recitation',
        ['user_id'],
        unique=False
    )

    # Restore the prior form of the plans search index
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index(
        'idx_plans_search',
        'plans',
        [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")],
        unique=False,
        postgresql_using='gin'
    )
    # ### end Alembic commands ###
