"""removed user_recitation table

Revision ID: 09bd37b1b454
Revises: 5cd30a42ee8b
Create Date: 2025-11-11 15:29:12.896869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bd37b1b454'
down_revision: Union[str, None] = '5cd30a42ee8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.String(length=255), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recitation_text_id', 'recitation', ['text_id'], unique=False)
    op.create_index('idx_recitation_title', 'recitation', ['title'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_recitation_title', table_name='recitation')
    op.drop_index('idx_recitation_text_id', table_name='recitation')
    op.drop_table('recitation')
    # ### end Alembic commands ###
