"""add plan_items

Revision ID: 15f5489e76e0
Revises: b973370162fa
Create Date: 2025-08-26 19:27:30.307954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f5489e76e0'
down_revision: Union[str, None] = 'b973370162fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('text', 'audio', 'video', 'image', 'source_reference', name='content_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_content_type', 'plan_tasks', ['content_type'], unique=False)
    op.create_index('idx_tasks_plan_item_order', 'plan_tasks', ['plan_item_id', 'display_order'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_tasks_plan_item_order', table_name='plan_tasks')
    op.drop_index('idx_tasks_content_type', table_name='plan_tasks')
    op.drop_table('plan_tasks')
    # ### end Alembic commands ###
