"""create recitation and user recitation table

Revision ID: 29a92b144385
Revises: 31e23892c909
Create Date: 2025-11-06 16:51:19.729996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a92b144385'
down_revision: Union[str, None] = '31e23892c909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
