"""add_table_User_plan_n_sub_task

Revision ID: 31e23892c909
Revises: 6efc11dc2b75
Create Date: 2025-11-05 17:03:28.748726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e23892c909'
down_revision: Union[str, None] = '6efc11dc2b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_day_completion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_id', name='uq_user_day_completion')
    )
    op.create_index('idx_user_day_completion_completed_at', 'user_day_completion', ['completed_at'], unique=False)
    op.create_index('idx_user_day_completion_user_day', 'user_day_completion', ['user_id', 'day_id'], unique=False)
    op.create_table('user_sub_task_completion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sub_task_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sub_task_id', name='uq_user_sub_task_completion')
    )
    op.create_index('idx_user_sub_task_completion_completed_at', 'user_sub_task_completion', ['completed_at'], unique=False)
    op.create_index('idx_user_sub_task_completion_user_sub_task', 'user_sub_task_completion', ['user_id', 'sub_task_id'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_user_sub_task_completion_user_sub_task', table_name='user_sub_task_completion')
    op.drop_index('idx_user_sub_task_completion_completed_at', table_name='user_sub_task_completion')
    op.drop_table('user_sub_task_completion')
    op.drop_index('idx_user_day_completion_user_day', table_name='user_day_completion')
    op.drop_index('idx_user_day_completion_completed_at', table_name='user_day_completion')
    op.drop_table('user_day_completion')
    # ### end Alembic commands ###
