"""create recitation and user recitation table

Revision ID: 3ef46899537a
Revises: 31e23892c909
Create Date: 2025-11-06 17:07:09.777605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef46899537a'
down_revision: Union[str, None] = '31e23892c909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recitation_title', 'recitation', ['title'], unique=False)
    op.create_table('user_recitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recitation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recitation_id'], ['recitation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recitation_id', name='uq_user_recitation_user_recitation')
    )
    op.create_index('idx_user_recitation_user_recitation_recitation', 'user_recitation', ['recitation_id'], unique=False)
    op.create_index('idx_user_recitation_user_recitation_user', 'user_recitation', ['user_id'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_user_recitation_user_recitation_user', table_name='user_recitation')
    op.drop_index('idx_user_recitation_user_recitation_recitation', table_name='user_recitation')
    op.drop_table('user_recitation')
    op.drop_index('idx_recitation_title', table_name='recitation')
    op.drop_table('recitation')
    # ### end Alembic commands ###
