"""update password_reset token_expiry to timezone aware

Revision ID: 402225950284
Revises: 6d6e2057a835
Create Date: 2025-08-30 17:37:03.072742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402225950284'
down_revision: Union[str, None] = '6d6e2057a835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update password_resets.token_expiry to timezone aware
    op.alter_column('password_resets', 'token_expiry',
                    existing_type=sa.DateTime(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert password_resets.token_expiry back to non-timezone aware
    op.alter_column('password_resets', 'token_expiry',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    # ### end Alembic commands ###
