"""add plan related tables

Revision ID: 42180c6e28e8
Revises: 402225950284
Create Date: 2025-09-02 17:10:40.745498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42180c6e28e8'
down_revision: Union[str, None] = '402225950284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authors_verified', 'authors', ['is_verified'], unique=False, postgresql_where=sa.text('is_verified = TRUE'))
    op.create_index(op.f('ix_authors_email'), 'authors', ['email'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'BO', 'ZH', name='languagecode'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'UNDER_REVIEW', name='planstatus'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plans_discovery', 'plans', ['tags', 'status'], unique=False)
    op.create_index('idx_plans_featured', 'plans', ['featured'], unique=False, postgresql_where=sa.text('featured = TRUE'))
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('idx_plans_tags', 'plans', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorites_user_plan', 'favorites', ['user_id', 'plan_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_number', name='uq_plan_items_plan_day')
    )
    op.create_index('idx_plan_items_plan_day', 'items', ['plan_id', 'day_number'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_plan_reviews_rating'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='uq_plan_reviews_user_plan')
    )
    op.create_index('idx_plan_reviews_plan_approved', 'reviews', ['plan_id', 'is_approved'], unique=False, postgresql_where=sa.text('is_approved = TRUE'))
    op.create_index('idx_plan_reviews_rating', 'reviews', ['plan_id', 'rating'], unique=False)
    op.create_table('user_plan_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED', name='userplanstatus'), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='uq_user_plan_progress_user_plan')
    )
    op.create_index('idx_user_progress_plan', 'user_plan_progress', ['plan_id'], unique=False)
    op.create_index('idx_user_progress_user_status', 'user_plan_progress', ['user_id', 'status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'AUDIO', 'VIDEO', 'IMAGE', 'SOURCE_REFERENCE', name='contenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_content_type', 'tasks', ['content_type'], unique=False)
    op.create_index('idx_tasks_plan_item_order', 'tasks', ['plan_item_id', 'display_order'], unique=False)
    op.create_table('user_task_completion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_user_task_completion')
    )
    op.create_index('idx_user_completion_completed_at', 'user_task_completion', ['completed_at'], unique=False)
    op.create_index('idx_user_completion_user_task', 'user_task_completion', ['user_id', 'task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_completion_user_task', table_name='user_task_completion')
    op.drop_index('idx_user_completion_completed_at', table_name='user_task_completion')
    op.drop_table('user_task_completion')
    op.drop_index('idx_tasks_plan_item_order', table_name='tasks')
    op.drop_index('idx_tasks_content_type', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_user_progress_user_status', table_name='user_plan_progress')
    op.drop_index('idx_user_progress_plan', table_name='user_plan_progress')
    op.drop_table('user_plan_progress')
    op.drop_index('idx_plan_reviews_rating', table_name='reviews')
    op.drop_index('idx_plan_reviews_plan_approved', table_name='reviews', postgresql_where=sa.text('is_approved = TRUE'))
    op.drop_table('reviews')
    op.drop_index('idx_plan_items_plan_day', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_favorites_user_plan', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_plans_tags', table_name='plans', postgresql_using='gin')
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.drop_index('idx_plans_featured', table_name='plans', postgresql_where=sa.text('featured = TRUE'))
    op.drop_index('idx_plans_discovery', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_authors_email'), table_name='authors')
    op.drop_index('idx_authors_verified', table_name='authors', postgresql_where=sa.text('is_verified = TRUE'))
    op.drop_table('authors')
    # ### end Alembic commands ###
