"""add_sub_tasks_table

Revision ID: 66cf74b76475
Revises: 8bd5f8181736
Create Date: 2025-10-08 05:03:28.422864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66cf74b76475'
down_revision: Union[str, None] = '8bd5f8181736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_tasks_content_type', table_name='tasks')
    op.drop_column('tasks', 'content')
    op.drop_column('tasks', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('content_type', postgresql.ENUM('TEXT', 'AUDIO', 'VIDEO', 'IMAGE', 'SOURCE_REFERENCE', name='contenttype'), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_tasks_content_type', 'tasks', ['content_type'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
