"""user profile and social_media account

Revision ID: 7493512afd74
Revises: 8cb8e9bed54a
Create Date: 2025-01-06 16:34:42.758216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7493512afd74'
down_revision: Union[str, None] = '8cb8e9bed54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'education')
    op.drop_column('users', 'location')
    op.drop_column('users', 'organization')
    op.drop_table('social_media_accounts')
    # ### end Alembic commands ###
