"""create user_recitations model

Revision ID: 77f12151114b
Revises: dc7082722fa8
Create Date: 2025-11-11 16:21:20.737440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f12151114b'
down_revision: Union[str, None] = 'dc7082722fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'text_id', name='uq_user_recitations_user_text')
    )
    op.create_index('idx_user_recitations_user_text_text', 'user_recitations', ['text_id'], unique=False)
    op.create_index('idx_user_recitations_user_text_user', 'user_recitations', ['user_id'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_user_recitations_user_text_user', table_name='user_recitations')
    op.drop_index('idx_user_recitations_user_text_text', table_name='user_recitations')
    op.drop_table('user_recitations')
    # ### end Alembic commands ###
