"""add organization title to the user

Revision ID: ce2f7ef7252f
Revises: 4dfbea70ddda
Create Date: 2025-01-06 18:15:40.944317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2f7ef7252f'
down_revision: Union[str, None] = '4dfbea70ddda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    # ### end Alembic commands ###
