"""remove_itam_day_number_uniqueness

Revision ID: d1af3ce7d70b
Revises: 38fe2996fa07
Create Date: 2025-10-31 18:14:08.656979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1af3ce7d70b'
down_revision: Union[str, None] = '38fe2996fa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_follows_created', table_name='user_follows')
    op.drop_index('idx_user_follows_follower', table_name='user_follows')
    op.drop_index('idx_user_follows_following', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_constraint('uq_plan_items_plan_day', 'items', type_='unique')
    op.create_unique_constraint('uq_plan_items_plan_day', 'items', ['plan_id'])
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_constraint('uq_plan_items_plan_day', 'items', type_='unique')
    op.create_unique_constraint('uq_plan_items_plan_day', 'items', ['plan_id', 'day_number'])
    op.create_table('user_follows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('follower_id <> following_id', name='no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='user_follows_follower_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='user_follows_following_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_follows_pkey'),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follow')
    )
    op.create_index('idx_user_follows_following', 'user_follows', ['following_id'], unique=False)
    op.create_index('idx_user_follows_follower', 'user_follows', ['follower_id'], unique=False)
    op.create_index('idx_user_follows_created', 'user_follows', ['created_at'], unique=False)
    # ### end Alembic commands ###
