"""removed recitation table

Revision ID: dc7082722fa8
Revises: 09bd37b1b454
Create Date: 2025-11-11 15:30:12.970267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7082722fa8'
down_revision: Union[str, None] = '09bd37b1b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recitation_text_id', table_name='recitation')
    op.drop_index('idx_recitation_title', table_name='recitation')
    op.drop_table('recitation')
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('recitation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recitation_pkey')
    )
    op.create_index('idx_recitation_title', 'recitation', ['title'], unique=False)
    op.create_index('idx_recitation_text_id', 'recitation', ['text_id'], unique=False)
    # ### end Alembic commands ###
