"""Add registration source as enum

Revision ID: ee064ae5f3f7
Revises: 4330352fc8ec
Create Date: 2024-12-01 11:29:36.612346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee064ae5f3f7'
down_revision: Union[str, None] = '4330352fc8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registration_source',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Enum('GOOGLE', 'FACEBOOK', 'EMAIL', name='registrationsource'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registration_source',
               existing_type=sa.Enum('GOOGLE', 'FACEBOOK', 'EMAIL', name='registrationsource'),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
