"""change table name to author_password_resets

Revision ID: f73050d2252f
Revises: a1b2c3d4e5f6
Create Date: 2025-09-20 12:31:36.708384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73050d2252f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['authors.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_password_resets_id'), 'author_password_resets', ['id'], unique=False)
    op.create_index(op.f('ix_author_password_resets_reset_token'), 'author_password_resets', ['reset_token'], unique=True)

    # Keep image_url columns at 1000; do not shrink types here.

    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')

    # No type changes were made to image_url in upgrade; nothing to revert.

    op.drop_index(op.f('ix_author_password_resets_reset_token'), table_name='author_password_resets')
    op.drop_index(op.f('ix_author_password_resets_id'), table_name='author_password_resets')
    op.drop_table('author_password_resets')
    # ### end Alembic commands ###