version: '3.8'
services:
  db-local:
    image: postgres:16-alpine
    container_name: pecha-database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pechaAdmin
      - POSTGRES_DB=pecha
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - ./data/database-local:/var/lib/postgresql/data
    networks:
      - pecha-network

  mongo-local:
    image: mongo:latest
    container_name: pecha-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pechaAdmin
      - MONGO_INITDB_DATABASE=pecha
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-local:/data/db  # Persist MongoDB data
    networks:
      - pecha-network

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    networks:
      - pecha-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: pecha-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - pecha-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  dbdata6:
  dragonflydata:
  elasticsearch-data:

networks:
  pecha-network:
    driver: bridge
