version: '3.8'
services:
  db-local:
    image: postgres:16-alpine
    container_name: pecha-database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pechaAdmin
      - POSTGRES_DB=pecha
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - ./data/database-local:/var/lib/postgresql/data
    networks:
      - pecha-network

  mongo-local:
    image: mongo:latest
    container_name: pecha-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pechaAdmin
      - MONGO_INITDB_DATABASE=pecha
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-local:/data/db  # Persist MongoDB data
    networks:
      - pecha-network

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
volumes:
  dbdata6:
  dragonflydata:

networks:
  pecha-network:
    driver: bridge
